#注意:在yml文件中添加value值时,value前面需要加一个空格
server:
  port: 8080
#  servlet.context-path: /GymManagerSystem

spring:
    mvc:
      view:
        prefix: /html/
        suffix: .html
    datasource:
        name: gym
        url: jdbc:mysql://127.0.0.1:3306/gym?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true 
        username: root 
        password: 251638
        # 使用druid数据源 
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gym.managesystem.demo.mapper

mapper:
  mappers:  com.gym.managesystem.demo.mapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check